# Generated by Django 3.2.7 on 2021-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210928_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='side_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='side_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
