# Generated by Django 3.2.7 on 2021-10-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modify_date',
        ),
    ]
