# Generated by Django 3.2.7 on 2021-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_top10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top10',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
