# Generated by Django 3.2.7 on 2021-10-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_top10_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top10',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='top10',
            name='question',
        ),
        migrations.RemoveField(
            model_name='top10',
            name='rank',
        ),
        migrations.AlterField(
            model_name='question',
            name='conflict',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
