# Generated by Django 3.2.7 on 2021-10-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211003_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='top10',
            name='remains',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='top10',
            name='tops',
            field=models.TextField(null=True),
        ),
    ]
