# Generated by Django 3.2.7 on 2021-10-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211003_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='top10',
            name='remains',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='top10',
            name='tops',
            field=models.TextField(default='[]'),
        ),
    ]
